version: "3.9"

networks:
  UnAd:
    external: false

services:
  redis-node-1:
    image: redis:7-alpine
    ports:
      - 7000:7000
      - 17000:17000
    networks:
      - UnAd
    hostname: redis-node-1
    volumes:
      - ./redis/7000:/redis
      - ./redis/start-redis.sh:/start-redis.sh
    command: ["/bin/sh", "/start-redis.sh"]
    environment:
      HOST_IP: ${HOST_IP}
  redis-node-2:
    image: redis:7-alpine
    ports:
      - 7001:7001
      - 17001:17001
    networks:
      - UnAd
    hostname: redis-node-2
    volumes:
      - ./redis/7001:/redis
      - ./redis/start-redis.sh:/start-redis.sh
    command: ["/bin/sh", "/start-redis.sh"]
    environment:
      HOST_IP: ${HOST_IP}

  redis-node-3:
    image: redis:7-alpine
    ports:
      - 7002:7002
      - 17002:17002
    networks:
      - UnAd
    hostname: redis-node-3
    volumes:
      - ./redis/7002:/redis
      - ./redis/start-redis.sh:/start-redis.sh
    command: ["/bin/sh", "/start-redis.sh"]
    environment:
      HOST_IP: ${HOST_IP}

  redis-node-4:
    image: redis:7-alpine
    ports:
      - 7003:7003
      - 17003:17003
    networks:
      - UnAd
    hostname: redis-node-4
    volumes:
  #     - ./redis/7003:/redis
  #     - ./redis/start-redis.sh:/start-redis.sh
  #   command: ["/bin/sh", "/start-redis.sh"]
  #   environment:
  #     HOST_IP: ${HOST_IP}

  # redis-node-5:
  #   image: redis:7-alpine
  #   ports:
  #     - 7004:7004
  #     - 17004:17004
  #   networks:
  #     - UnAd
  #   hostname: redis-node-5
  #   volumes:
  #     - ./redis/7004:/redis
  #     - ./redis/start-redis.sh:/start-redis.sh
  #   command: ["/bin/sh", "/start-redis.sh"]
  #   environment:
  #     HOST_IP: ${HOST_IP}
  
  # redis-node-6:
  #   image: redis:7-alpine
  #   ports:
  #     - 7005:7005
  #     - 17005:17005
  #   networks:
  #     - UnAd
  #   hostname: redis-node-6
  #   volumes:
  #     - ./redis/7005:/redis
  #     - ./redis/start-redis.sh:/start-redis.sh
  #   command: ["/bin/sh", "/start-redis.sh"]
  #   environment:
  #     HOST_IP: ${HOST_IP}
  
  # redis-cluster-creator:
  #   image: redis:7-alpine
  #   ports:
  #     - 6999:6999
  #   networks:
  #     - UnAd
  #   command: redis-cli -p 7000 --cluster create redis-node-1:7000 redis-node-2:7001 redis-node-3:7002 redis-node-4:7003 redis-node-5:7004 redis-node-6:7005 --cluster-replicas 1 --cluster-yes
  #   depends_on:
  #     - redis-node-1
  #     - redis-node-2
  #     - redis-node-3
  #     - redis-node-4
  #     - redis-node-5
  #     - redis-node-6
  
  # redis-insight:
  #   image: redislabs/redisinsight
  #   ports:
  #     - 8001:8001
  #   networks:
  #     - UnAd
  #   volumes:
  #     - ./redisinsight:/db
  #   depends_on:
  #     - redis-cluster-creator
