version: "3.9"

networks:
  UnAd:
    external: false

services:
  signup-site:
    networks:
      - UnAd
    build:
      context: ./
      dockerfile: ./web/unad-web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - HOST=0.0.0.0
    env_file:
      - ./web/unad-web/.env.docker

  user-api:
    networks:
      - UnAd
    build:
      context: ./dotnet
      dockerfile: ./UserApi.Dockerfile
      secrets:
        - graphmonitorheaders
      args:
        - GRAPH_MONITOR_URL=http://host.docker.internal:5145
    ports:
      - "5300:5300"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORTS=5300
    env_file:
      - ./dotnet/.env.docker

  graphql-gateway:
    networks:
      - UnAd
    build:
      context: ./dotnet
      dockerfile: ./GraphQLGateway.Dockerfile
      secrets:
        - graphmonitorheaders
      args:
        - GRAPH_MONITOR_URL=http://host.docker.internal:5145
    ports:
      - "5100:5100"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORTS=5100
    env_file:
      - ./dotnet/.env.docker
    depends_on:
      - user-api

secrets:
  graphmonitorheaders:
    file: ./dotnet/GraphMonitor/headers
