networks:
  UnAd:
    external: false

services:

  redis:
    image: redis:7-alpine
    networks:
      - UnAd
    ports:
      - 6379:6379
      
  postgres:
    build:
      context: ./db
    networks:
      - UnAd
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env.docker
  
  db-migrator:
    build:
      context: ./dotnet/
      dockerfile: Migrator.Dockerfile
    networks:
      - UnAd
    depends_on:
      - postgres
    env_file:
      - ./dotnet/.env.docker

  db-seeder:
    build:
      context: ./dotnet
      dockerfile: DbSeeder.Dockerfile
    networks:
      - UnAd
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dotnet/.env.docker

  graph-monitor:
    networks:
      - UnAd
    build:
      context: ./dotnet/GraphMonitor
    ports:
      - "5145:5145"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORTS=5145
    env_file:
      - ./dotnet/.env.docker

  unad-functions:
    networks:
      - UnAd
    build:
      context: ./dotnet
      dockerfile: UnAd.Functions.Dockerfile
    ports:
      - "7071:7071"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORTS=7071
    env_file:
      - ./dotnet/.env.docker
