version: "3.9"

networks:
  UnAd:
    external: false

services:

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - UnAd
      
  postgres:
    networks:
      - UnAd
    build:
      context: ./db
    ports:
      - "5432:5432"
    env_file:
      - ./db/.env.docker

  migrator:
    build:
      context: ./dotnet/
      dockerfile: Migrator.Dockerfile
    networks:
      - UnAd
    depends_on:
      - postgres
    env_file:
      - ./db/.env.docker

  # pgadmin:
  #   networks:
  #     - UnAd
  #   image: dpage/pgadmin4
  #   ports:
  #     - "5431:5431"
  #   env_file:
  #     - ./db/.env.docker

  # graph-monitor:
  #   networks:
  #     - UnAd
  #   restart: always
  #   build:
  #     context: ./dotnet/GraphMonitor/GraphMonitor
  #     dockerfile: Dockerfile.local
  #   ports:
  #     - "5145:5145"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:5145
  #   env_file:
  #     - ./dotnet/.env.docker
  #   healthcheck:
  #     test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/5145' || exit 1
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   depends_on:
  #     - redis

# volumes:
#   postgres:
#     external: false
