@UnAd.Functions_HostAddress = http://localhost:7071

POST {{UnAd.Functions_HostAddress}}/api/MessageHandler?code=ut7NTvdehnwAi5NVqlovNGGuSH0beEeq
Accept: application/json
Content-Type: application/x-www-form-urlencoded

Body=COMMANDS&From=%2B19044389199
###
