
resource "local_sensitive_file" "base_dotenv" {
  filename = "./dotenv/.env.base"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    AWS_REGION="${var.region}"
  EOT
}

resource "local_sensitive_file" "dotenv_rds" {
  filename = "./dotenv/.env.rds"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    RDS_ENDPOINT="${module.aws.rds_cluster_endpoint}"
    RDS_PASSWORD="${module.aws.rds_cluster_password}"
  EOT
}

resource "local_sensitive_file" "dotenv_ec2" {
  filename = "./dotenv/.env.ec2"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    JUMPBOX_HOST="${module.aws.jumpbox_host}"
  EOT
}

resource "local_sensitive_file" "dotenv_ecs" {
  filename = "./dotenv/.env.ecs"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    GRAPH_MONITOR_API_KEY="${module.aws.graph_montitor_api_key}"
  EOT
}

resource "local_sensitive_file" "dotenv_redis" {
  filename = "./dotenv/.env.redis"
  content  = <<-EOT
    # This file is automatically generated by terraform.
    # Do not edit this file directly.
    # Instead, update your project-specific .env.local file
    REDIS_CLUSTER_ENDPOINTS="${module.aws.redis_endpoints}"
    REDIS_CLUSTER_NODES="${module.aws.redis_nodes}"
    REDIS_PASSWORD="${module.aws.redis_password}"
    REDIS_USERNAME="${module.aws.redis_username}"
    REDIS_PORT="${module.aws.redis_port}"
  EOT
}


