// <auto-generated />
using UnAd.Data.Users;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace UnAd.Data.Users {
    [DbContext(typeof(UserDbContext))]
    [Migration("20230902001850_InitialCreate")]
    partial class InitialCreate {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnAd.Data.Users.Models.Role", b => {
                b.Property<string>("Id")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("id");

                b.HasKey("Id")
                    .HasName("role_pkey");

                b.ToTable("role", (string)null);
            });

            modelBuilder.Entity("UnAd.Data.Users.Models.User", b => {
                b.Property<string>("Id")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("id");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("email");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("name");

                b.Property<string>("RoleId")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("user_pkey");

                b.HasIndex("RoleId");

                b.ToTable("user", (string)null);
            });

            modelBuilder.Entity("UnAd.Data.Users.Models.User", b => {
                b.HasOne("UnAd.Data.Users.Models.Role", "Role")
                    .WithMany("Users")
                    .HasForeignKey("RoleId")
                    .IsRequired()
                    .HasConstraintName("fk_role");

                b.Navigation("Role");
            });

            modelBuilder.Entity("UnAd.Data.Users.Models.Role", b => {
                b.Navigation("Users");
            });
#pragma warning restore 612, 618
        }
    }
}


