# https://icons.terrastruct.com/ for icons

ElastiCache: {
  shape: image
  icon: ./icons/elasticache.svg
  tooltip: "Redis"
}

Twilio: {
  label: ""
  shape: image
  icon: ./icons/twilio.svg
}

Stripe: {
  label: ""
  shape: image
  icon: ./icons/stripe.svg
}

Browser: {
  shape: image
  icon: ./icons/browser.svg
}

RDS: {
  icon: ./icons/aurora.svg
  label: "RDS"
  userdb: {
    label: "userdb"
    icon: ./icons/postgres.svg
    shape: cylinder
    label.near: bottom-center
    icon.near: top-center
    style.multiple: true
  }
}

ECS: {
  icon: "./icons/ecs.svg"
  unad-cluster: {
    unad-functions: {
      shape: image
      icon: ./icons/ecs-instance.svg
    }
    signup-site: {
      shape: image
      icon: ./icons/ecs-instance.svg
    }
  }
}

S3: {
  icon: ./icons/s3.svg
  link: "/services/s3/#amazon-s3"
  Cloudwatch: {
    shape: image
    icon: ./icons/cloudwatch.svg
  }
}

ECS.unad-cluster -> RDS.userdb
ECS.unad-cluster -> ElastiCache
ECS.unad-cluster -> S3.Cloudwatch: Logs

Twilio -> ECS.unad-cluster.unad-functions: Webhooks
Stripe -> ECS.unad-cluster.unad-functions: Webhooks

Browser -> ECS.unad-cluster.signup-site: signup.unad.tech
