FROM mcr.microsoft.com/dotnet/sdk:8.0-bullseye-slim AS build

WORKDIR /src
COPY . ./
RUN dotnet restore "GraphMonitor.csproj"
RUN dotnet publish "GraphMonitor.csproj" -c Release -o /src/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /src/publish .
ENTRYPOINT ["dotnet", "GraphMonitor.dll"]
