name: Migrate DB on SSH Tunnel

on:
  workflow_dispatch:

env:
  CONTEXT_PATH: dotnet
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
      
      - name: Install dependencies
        run: dotnet restore dotnet/UnAd.Data.Migrator.sln

      - name: Generate Bundle
        run: |
          dotnet tool restore
          dotnet ef migrations bundle \
          --project ./UnAd.Data/UnAd.Data.csproj \
          --startup-project ./tools/UnAd.Data.Migrator/UnAd.Data.Migrator.csproj \
          --self-contained -r linux-x64
          chmod +x efbundle
        working-directory: dotnet
    
      - name: Setup SSH and Tunnel
        run: |
          # Setup SSH key stored in GitHub Secrets
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMPBOX_SSH_PRIVATE_KEY }}" > ~/.ssh/jumpbox_ed25519
          chmod 600 ~/.ssh/jumpbox_ed25519
          # Setup SSH tunnel
          ssh -i ~/.ssh/jumpbox_ed25519 -o StrictHostKeyChecking=no -L 5050:${{ vars.DB_HOST }}:${{ vars.DB_PORT }} ubuntu@${{ vars.JUMPBOX_HOST }} -N & echo $! > ssh_tunnel.pid
          # Exceute migrations
          dotnet/efbundle --connection "Host=localhost;Port=5050;Database=unad;Username=unad;Password=${{ secrets.DB_PASS }}"
          # Kill SSH tunnel
          kill -9 $(lsof -t -i :5050)

      