name: Seed DB on SSH Tunnel

on:
  workflow_dispatch:

env:
  CONTEXT_PATH: dotnet
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
      
      - name: Install dependencies
        run: dotnet restore dotnet/DbSeeder.sln
    
      - name: Setup SSH Tunnel and Run Migrations
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.JUMPBOX_SSH_PRIVATE_KEY }}" > ~/.ssh/jumpbox_ed25519
          chmod 600 ~/.ssh/jumpbox_ed25519

          ssh -i ~/.ssh/jumpbox_ed25519 -o StrictHostKeyChecking=no -L 5050:${{ vars.REDIS_HOST }}:${{ vars.REDIS_PORT }} ubuntu@${{ vars.JUMPBOX_HOST }} -N & echo $! > ssh_tunnel.pid

          ConnectionStrings__UserDb="Host=localhost;Port=5050;Username=unad;Password=${{ secrets.DB_PASS }};Timeout=60;Database=userdb;" dotnet run --project dotnet/DbSeeder/DbSeeder.csproj

          kill -9 $(lsof -t -i :5050)
        env:
          REDIS_URL: "localhost:5050,abortConnect=false"
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
