name: Build and Deploy Graph Monitor to ECR and Lambda

on:
  workflow_dispatch:

env:
  ECR_REPOSITORY: unad/graph-monitor
  LAMBDA_FUNCTION: graph-monitor
  PROJECT_PATH: serverless/GraphMonitor/GraphMonitor
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
        
      - name: Install tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Deploy PUT
        run: |
          dotnet lambda deploy-function graph-monitor-post \
          --config-file .\serverless.template \
          --function-runtime dotnet8 \
          --function-role lambda_execution_role \
          --function-memory-size 256 \
          --function-timeout 60 \
          --function-handler GraphMonitor::GraphMonitor.StoreUrlFunction_StoreUrl_Generated::StoreUrl
          working-directory: ${{ env.PROJECT_PATH }}

      - name: Deploy GET
        run: |
          dotnet lambda deploy-function graph-monitor-get \
          --config-file .\serverless.template \
          --function-runtime dotnet8 \
          --function-role lambda_execution_role \
          --function-memory-size 256 \
          --function-timeout 60 \
          --function-handler GraphMonitor::GraphMonitor.GetUrlFunction_GetUrl_Generated::GetUrl
        working-directory: ${{ env.PROJECT_PATH }}
