name: PR checks for signup-site

on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/unad-web/**'
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        working-directory: web/unad-web
      